#!/bin/bash
# Refresh gba/ from the gba_wasm tree.
#
#   ./sync-gba.sh [path-to-gba_wasm]
#   ./sync-gba.sh --no-build [path]     # copy what is already in dist/
#
# gba/ is a build product and nothing else: tools/bundle.py's output from
# gba_wasm, copied in unedited. It is committed here because this site is
# served straight out of the repository and nothing here builds a megabyte of
# emscripten-compiled mGBA -- but it is not source, and editing it here only
# means the next refresh throws the edit away. The emulator changes in
# gba_wasm; this brings the change over.
#
# Unlike bike/, building needs nothing but python3: gba_wasm keeps the
# compiled core checked in, and bundle.py only inlines it. So what lands here
# really can be rebuilt from the commit UPSTREAM names.
#
# The single edit is a rename. bundle.py writes dist/gba-wasm.html, which is
# the name to email someone; serving a directory is what this site does, so it
# arrives as gba/index.html and the tile links to gba/ like it links to bike/.
# The roms/ directory beside it is not incidental -- the page fetches the game
# from there on a first visit, so the two travel together.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

BUILD=1
SRC=""
for a in "$@"; do
  case "$a" in
    --no-build) BUILD=0 ;;
    -h|--help)  sed -n '2,22p' "$0"; exit 0 ;;
    *)          SRC="$a" ;;
  esac
done

# Sibling checkout by default; $GBA_WASM or an argument override it.
if [ -z "$SRC" ]; then SRC="${GBA_WASM:-$HERE/../gba_wasm}"; fi
[ -d "$SRC" ] || { echo "no gba_wasm at $SRC (pass a path or set GBA_WASM)" >&2; exit 1; }
SRC="$(cd "$SRC" && pwd)"
[ -f "$SRC/tools/bundle.py" ] || { echo "$SRC does not look like gba_wasm" >&2; exit 1; }

OUT="$SRC/dist"

if [ "$BUILD" = 1 ]; then
  command -v python3 >/dev/null || { echo "python3 not found; --no-build to copy dist/ as it stands" >&2; exit 1; }
  echo "==> bundling $SRC"
  (cd "$SRC" && python3 tools/bundle.py)
fi

for f in gba-wasm.html roms/connect4.gba; do
  [ -s "$OUT/$f" ] || { echo "$OUT/$f is missing or empty -- bundle first" >&2; exit 1; }
done

echo "==> copying $OUT -> $HERE/gba"
rsync -a --delete --exclude UPSTREAM --exclude index.html "$OUT/" "$HERE/gba/"
mv "$HERE/gba/gba-wasm.html" "$HERE/gba/index.html"
cmp -s "$OUT/gba-wasm.html" "$HERE/gba/index.html"
cmp -s "$OUT/roms/connect4.gba" "$HERE/gba/roms/connect4.gba"

# What this copy came from. Everything the bundle inlines is committed in
# gba_wasm -- the single-threaded core included -- so unlike bike/ this commit
# is enough to reproduce what is sitting here.
rev=$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)
sub=$(git -C "$SRC" log -1 --pretty=%s 2>/dev/null || echo unknown)
[ -z "$(git -C "$SRC" status --porcelain 2>/dev/null)" ] || rev="$rev-dirty"
core=$(shasum -a 256 "$SRC/web/vendor/mgba-single-thread.wasm" 2>/dev/null | cut -c1-12)

cat > "$HERE/gba/UPSTREAM" <<EOF
Generated by sync-gba.sh -- do not edit anything in this directory.

gba/ is tools/bundle.py's output from gba_wasm, copied in whole and unedited;
the one change is the name, gba-wasm.html arriving as index.html so the
directory serves. roms/connect4.gba travels with it because the page fetches
the game from there on a first visit. Change the emulator there and run
./sync-gba.sh to bring it here.

source     $SRC
commit     $rev  $sub
core       mgba-single-thread.wasm sha256:$core, committed in gba_wasm
built      $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo
cat "$HERE/gba/UPSTREAM"
echo
du -sh "$HERE/gba"
git -C "$HERE" status --short gba || true
