#!/bin/bash
# Refresh bloons/ from the bloons tree.
#
#   ./sync-bloons.sh [path-to-bloons]
#   ./sync-bloons.sh --no-build [path]     # copy what is already in web/
#
# bloons/ is a build product and nothing else: build_web.sh's output from
# bloons, copied in unedited -- one page per game (bloons-td-1.html through
# bloons-td-4.html) that fills whatever box it is framed in, the original SWFs
# beside them, and the Ruffle web build they all share. It is committed here
# because this site is served straight out of the repository; editing it here
# only means the next refresh throws the edit away.
#
# Building downloads the newest Ruffle nightly with gh (or the release named
# by $RUFFLE_TAG), so what lands here is pinned by the Ruffle version UPSTREAM
# records rather than by the bloons commit alone.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

BUILD=1
SRC=""
for a in "$@"; do
  case "$a" in
    --no-build) BUILD=0 ;;
    -h|--help)  sed -n '2,16p' "$0"; exit 0 ;;
    *)          SRC="$a" ;;
  esac
done

# Sibling checkout by default; $BLOONS or an argument override it.
if [ -z "$SRC" ]; then SRC="${BLOONS:-$HERE/../bloons}"; fi
[ -d "$SRC" ] || { echo "no bloons at $SRC (pass a path or set BLOONS)" >&2; exit 1; }
SRC="$(cd "$SRC" && pwd)"
[ -x "$SRC/build_web.sh" ] || { echo "$SRC does not look like bloons" >&2; exit 1; }

OUT="$SRC/web"

if [ "$BUILD" = 1 ]; then
  command -v gh >/dev/null || { echo "gh not found; --no-build to copy web/ as it stands" >&2; exit 1; }
  echo "==> building $SRC"
  "$SRC/build_web.sh"
fi

for n in 1 2 3 4; do
  for f in "bloons-td-$n.html" "games/bloons-td-$n.swf"; do
    [ -s "$OUT/$f" ] || { echo "$OUT/$f is missing or empty -- build first" >&2; exit 1; }
  done
done
[ -s "$OUT/ruffle/ruffle.js" ] || { echo "$OUT/ruffle/ruffle.js is missing -- build first" >&2; exit 1; }

echo "==> copying $OUT -> $HERE/bloons"
rsync -a --delete --exclude UPSTREAM "$OUT/" "$HERE/bloons/"
diff -rq --exclude UPSTREAM "$OUT" "$HERE/bloons" >/dev/null

rev=$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)
sub=$(git -C "$SRC" log -1 --pretty=%s 2>/dev/null || echo unknown)
[ -z "$(git -C "$SRC" status --porcelain 2>/dev/null)" ] || rev="$rev-dirty"
ruffle=$(sed -n 's/.*"version":"\([^"]*\)".*/\1/p' "$OUT/ruffle/package.json")

cat > "$HERE/bloons/UPSTREAM" <<EOF
Generated by sync-bloons.sh -- do not edit anything in this directory.

bloons/ is build_web.sh's output from bloons, copied in whole and unedited.
Each bloons-td-<n>.html plays one game and fills the box it is framed in.
Change the pages there and run ./sync-bloons.sh to bring them here.

source     $SRC
commit     $rev  $sub
ruffle     $ruffle
built      $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo
cat "$HERE/bloons/UPSTREAM"
echo
du -sh "$HERE/bloons"
git -C "$HERE" status --short bloons || true
