#!/bin/bash
# Refresh bike/ from the bike_or_die tree.
#
#   ./sync-bike.sh [path-to-bike_or_die]
#   ./sync-bike.sh --no-build [path]     # copy what is already in build/web
#
# bike/ is a build product and nothing else: the whole of bike_or_die's
# tools/make_web.sh output, copied in unedited. It is committed here because
# this site is served straight out of the repository and the game is 37 MB of
# wasm that no step here builds -- but it is not source, and editing it here
# only means the next refresh throws the edit away. The game changes in
# bike_or_die; this brings the change over.
#
# The one thing not copied is pumpkin.html, which make_web.sh writes as a
# second name for the same bytes as index.html. Serving the directory is what
# this site does, so index.html is the name that gets used and the duplicate is
# 18 KB of nothing.
#
# Building needs emscripten in PATH, and the game files bike_or_die keeps in
# files/ -- neither of which lives here, which is the other reason bike/ is
# committed rather than made.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

BUILD=1
SRC=""
for a in "$@"; do
  case "$a" in
    --no-build) BUILD=0 ;;
    -h|--help)  sed -n '2,20p' "$0"; exit 0 ;;
    *)          SRC="$a" ;;
  esac
done

# Sibling checkout by default; $BIKE_OR_DIE or an argument override it.
if [ -z "$SRC" ]; then SRC="${BIKE_OR_DIE:-$HERE/../bike_or_die}"; fi
[ -d "$SRC" ] || { echo "no bike_or_die at $SRC (pass a path or set BIKE_OR_DIE)" >&2; exit 1; }
SRC="$(cd "$SRC" && pwd)"
[ -x "$SRC/tools/make_web.sh" ] || { echo "$SRC does not look like bike_or_die" >&2; exit 1; }

OUT="$SRC/build/web"

if [ "$BUILD" = 1 ]; then
  command -v emcc >/dev/null || { echo "emcc not found in PATH; --no-build to copy build/web as it stands" >&2; exit 1; }
  echo "==> building $SRC"
  "$SRC/tools/make_web.sh"
fi

for f in index.html pumpkin.js pumpkin.wasm pumpkin.data coi-serviceworker.js; do
  [ -s "$OUT/$f" ] || { echo "$OUT/$f is missing or empty -- build first" >&2; exit 1; }
done

echo "==> copying $OUT -> $HERE/bike"
rsync -a --delete --exclude pumpkin.html --exclude UPSTREAM "$OUT/" "$HERE/bike/"
diff -rq --exclude pumpkin.html --exclude UPSTREAM "$OUT" "$HERE/bike" >/dev/null

# What this copy came from. The vendored PumpkinOS is not in bike_or_die's
# history either -- setup.sh clones it and applies patches/pumpkinos.patch --
# so a tree carrying more than the patch is worth saying out loud: it means
# what is in bike/ cannot be rebuilt from that commit alone.
rev=$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)
sub=$(git -C "$SRC" log -1 --pretty=%s 2>/dev/null || echo unknown)
[ -z "$(git -C "$SRC" status --porcelain 2>/dev/null)" ] || rev="$rev-dirty"
pk="matches patches/pumpkinos.patch"
if [ -d "$SRC/vendor/PumpkinOS" ]; then
  git -C "$SRC/vendor/PumpkinOS" diff HEAD | diff -q - "$SRC/patches/pumpkinos.patch" >/dev/null 2>&1 \
    || pk="CARRIES CHANGES BEYOND patches/pumpkinos.patch"
fi

cat > "$HERE/bike/UPSTREAM" <<EOF
Generated by sync-bike.sh -- do not edit anything in this directory.

bike/ is tools/make_web.sh's output from bike_or_die, copied in whole and
unedited (less pumpkin.html, a duplicate of index.html). Change the game there
and run ./sync-bike.sh to bring it here.

source     $SRC
commit     $rev  $sub
pumpkinos  $pk
built      $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo
cat "$HERE/bike/UPSTREAM"
echo
du -sh "$HERE/bike"
git -C "$HERE" status --short bike || true
